# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ICA <- function(XX, mm, WW, gauss_noise = 0L, generalized = 1L, c = 1.) {
    .Call('_ICAA_ICA', PACKAGE = 'ICAA', XX, mm, WW, gauss_noise, generalized, c)
}

